# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'textAll' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for textAll
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'Reveal-SDK', '~> 7', :configurations => ['Debug']
end
